[package]
name = "nzscq"
version = "0.4.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/nzsc-org/nzscq"
description = "Core logic for NZSCQ."

[dependencies]
